language: node_js
node_js:
  - 6 # to be removed 2019-04-01
  - lts/*
  - node

before_script:
  - npm run bootstrap
  - npm run build

script:
  - WITH_COVERAGE=1 npm test

after_success:
  -  npm run coverage.submit
